# Generated by Django 4.1 on 2022-09-15 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='tag_name', max_length=255, verbose_name='tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_value',
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1998, 7, 20, 0, 0), help_text='date_of_birth', verbose_name='Birth'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(help_text='Contact_name', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Phone', 'phones'), ('email', 'Email'), ('Telegram', 'telegram'), ('LinkedIn', 'Linkedin')], default='Phone', max_length=255, verbose_name='Contact_type')),
                ('contact_value', models.CharField(max_length=255, unique=True, verbose_name='Contact_value')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='apps_phone.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='apps_phone.tag'),
        ),
    ]
